### ISSUE TITLE
documentation: overview of methods

### ISSUE THREAD

**Issue by Atalroghman** [scikit-activeml/scikit-activeml#122]
JSON file to generate an example page in the documentation 
- [x] Exemplary file for a method of the pool-based strategies, and generate rst file from json file to have an example page with plots in the documentation.
- [x] Final goal is to have a json file that has all the query strategies (pool-based, stream-based …) and we will get access to it through a python file to get an example page with plots in the documentation.
- [ ] Download button for the references 
- [x] Multi JSON files for each module. 
- [x] Overview page, some important buttons on it .i.e name, class, citation key.
- [x] Generate GIF load it on Matplot lib and do function animation. 
- [x] Precalculating the GIF or automatically generating it.

**Comment by dakot** [comment]
- [ ] clean up generation of overview, documentation by @Pascal112

**Comment by dakot** [comment]
done
