### ISSUE TITLE
Complete path or only class name in documentation

### ISSUE THREAD

**Issue by christoph14** [scikit-activeml/scikit-activeml#160]
E.g. clf : SklearnClassifier or skactiveml.classifier.SklearnClassifier

**Comment by mmuejde** [comment]
- https://scikit-learn.org/stable/modules/classes.html#module-sklearn.linear_model
- https://scikit-learn.org/stable/modules/classes.html#module-sklearn.neighbors
- https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AffinityPropagation.html#sklearn.cluster.AffinityPropagation
- https://scikit-learn.org/stable/modules/classes.html#module-sklearn.feature_selection
- ...
