### ISSUE TITLE
meaning of utilities

### ISSUE THREAD

**Issue by LukasLuehrs** [scikit-activeml/scikit-activeml#167]
Should the sample indices be maximizer of the utilities?
If this is the case, then include into general test?
Specify meaning in documentation?

**Comment by dakot** [comment]
Should be discussed again

**Comment by dakot** [comment]
should always be maximized. 
- [ ] mention in dev guide. 
- [ ] mention if utility has been changed for a specific strategy (note in `query` - returns)
