### ISSUE TITLE
Versioning the documentation

### ISSUE THREAD

**Issue by mehmetmuejde** [scikit-activeml/scikit-activeml#182]

**Comment by mmuejde** [comment]
https://sphinxcontrib-versioning.readthedocs.io/en/latest/tutorial.html

**Comment by mmuejde** [comment]
https://holzhaus.github.io/sphinx-multiversion/master/index.html

**Comment by mmuejde** [comment]
https://github.com/Smile-SA/sphinx-versions

**Comment by mmuejde** [comment]
Custom solution?

**Comment by mherde** [comment]
Duplicate of issue #305
