### ISSUE TITLE
Pool based active learning for regression

### ISSUE THREAD

**Issue by LukasLuehrs** [scikit-activeml/scikit-activeml#226]
0.) Small presentation

1.) Packages:
   Maybe:
      pool/
         classifier-qs
         regression-qs
         rest

2.) How to name `conditional_estimator`? is the equivalent to `probabilistic classifier` for regression.

**Comment by mherde** [comment]
Which notebooks are useful:
- Evaluation example (comparison on multiple (real-world) data sets of multiple strategies)
- Notebook about possible integration methods (linear, quantile, monte-carlo, scipy) including explanations
- .json visualization (@Pascal112) how much effort is needed?

**Comment by mherde** [comment]
Plan for next meeting:
- Starting with plot of structure fo regression
- Inspecting base classes: `SkactivemlRegressor`, `SkactivemlCondiationalEstimator`, `SklearnRegressor`, `SklearnConditionalEstimator`
- Overview of implemented active learning strategies for regression including simple categorization
- Brief demonstration of subset of strategies
- Brief demonstration and explanation of integration, if not done before
- discuss open points (see comments above)

**Comment by mherde** [comment]
QBC with default ensemble construction technique, e.g., bootstrapping?

**Comment by mherde** [comment]
How to handle general pool test in comparison to classification?
