### ISSUE TITLE
Restructure tests such that tests for common arguments (missing_label, classes, etc.) are inherited via an abstract test class

### ISSUE THREAD

**Issue by tpham93** [scikit-activeml/scikit-activeml#230]

**Comment by mherde** [comment]
The following sub-packages must be restructured according to the new test design:
- [x] `pool`,
- [ ] `stream`,
  - [ ] query strategies,
  - [ ] budget managers,
- [ ] `classifier`,
- [ ] `regressor`.

**Comment by mherde** [comment]
Duplicate of #303
