### ISSUE TITLE
DUAL (Donmez 2007)

### ISSUE THREAD

**Issue by Pascal112** [scikit-activeml/scikit-activeml#261]

**Comment by Pascal112** [comment]
Paper:
https://www.researchgate.net/profile/Jaime-Carbonell/publication/221112363_Dual-Strategy_Active_Learning/links/541c32300cf241a65a0bc60d/Dual-Strategy-Active-Learning.pdf?origin=publication_detail

**Comment by mherde** [comment]
Already [part](https://scikit-activeml.github.io/scikit-activeml-docs/generated/sphinx_gallery_examples/pool/plot-UncertaintySampling-Dual_strategy_for_Active_Learning.html#sphx-glr-generated-sphinx-gallery-examples-pool-plot-uncertaintysampling-dual-strategy-for-active-learning-py) of the repository.
