### ISSUE TITLE
DWUS (Nguyen 2004, Donmez 2007)

### ISSUE THREAD

**Issue by Pascal112** [scikit-activeml/scikit-activeml#262]

**Comment by mherde** [comment]
Already [part](https://scikit-activeml.github.io/scikit-activeml-docs/generated/sphinx_gallery_examples/pool/plot-UncertaintySampling-Density-weighted_Uncertainty_Sampling.html#sphx-glr-generated-sphinx-gallery-examples-pool-plot-uncertaintysampling-density-weighted-uncertainty-sampling-py) of the repository.
