### ISSUE TITLE
Guidelines for unlabeled class

### ISSUE THREAD

**Issue by dakot** [scikit-activeml/scikit-activeml#27]
Should all selection strategies have argument: unlabeled class?

**Comment by dakot** [comment]
YES: it is called: missing_label

please import constant MISSING_LABEL from utils

**Comment by mherde** [comment]
@dakot  What about strategies that take a classifier as input? Currently, all our classifieres have the attribute missing_label which could be used by the QueryStrategy. Otherwise, we have to check whether `clf.missing_label` is equal to the `missing_label` provided as parameter.

**Comment by dakot** [comment]
moved to wiki
