### ISSUE TITLE
Make framework Pep8 compliant

### ISSUE THREAD

**Issue by tpham93** [scikit-activeml/scikit-activeml#33]
Scikit-learn uses PEP8 (https://www.python.org/dev/peps/pep-0008/), i.e., flake8 as linting tool, to standardize its code.

**Comment by dakot** [comment]
Write guidelines

**Comment by dakot** [comment]
include to CI

**Comment by tpham93** [comment]
Matched the flake8 configuration we had before with the one used in sklearn (removed --max-complexity=10 and --max-line-length=127)
However, linting warnings are not reflected in the action yet, as here is the current list of flake8 violations, while it shows that it passed (https://github.com/scikit-activeml/scikit-activeml/runs/1066677253?check_suite_focus=true):
- 1     E125 continuation line with same indent as next logical line
- 1     E127 continuation line over-indented for visual indent
- 1     E128 continuation line under-indented for visual indent
- 21    E225 missing whitespace around operator
- 76    E231 missing whitespace after ','
- 3     E251 unexpected spaces around keyword / parameter equals
- 1     E261 at least two spaces before inline comment
- 12    E265 block comment should start with '# '
- 5     E302 expected 2 blank lines, found 1
- 4     E303 too many blank lines (6)
- 361   E501 line too long (101 > 79 characters)
- 4     F401 'sklearn.utils.check_random_state' imported but unused
- 2     F841 local variable 'P' is assigned to but never used
- 2     W291 trailing whitespace
- 3     W292 no newline at end of file
- 7     W293 blank line contains whitespace
- 3     W391 blank line at end of file

**Comment by dakot** [comment]
moved to wiki
