### ISSUE TITLE
Wie wrappen wir alle möglichen sklearn classifier?

### ISSUE THREAD

**Issue by dakot** [scikit-activeml/scikit-activeml#34]
- mega meta wrapper?
- einzelne wrapper?

**Comment by mherde** [comment]
@dakot May I remove the `semi_supervised package` including the `IgnUnlabeledWrapper` class. Do you have an idea which package would be suitable for the `SklearnClassifier` wrapper? Currently, it is in `utils`.

**Comment by dakot** [comment]
Yes

**Comment by dakot** [comment]
idea: classifier
