### ISSUE TITLE
Error check_missing_label

### ISSUE THREAD

**Issue by Pascal112** [scikit-activeml/scikit-activeml#35]
check_missing_label throws an error. Example in scikit-activeml\examples\error_check_missing_label.ipynb

**Comment by mherde** [comment]
On my machine, it works (see below).
![image](https://user-images.githubusercontent.com/27784041/91062822-76d7ea80-e62d-11ea-99f2-c0b0c7ef9ba0.png)
@Pascal112  Which numpy and scikit-learn version do you use?
The requirements expects `scikit-learn==0.23.2` and `numpy==1.19.1`.

**Comment by Pascal112** [comment]
@mherde I use the same versions.

**Comment by Pascal112** [comment]
numpy-base was out of date.
