### ISSUE TITLE
Automate creation of wiki

### ISSUE THREAD

**Issue by tpham93** [scikit-activeml/scikit-activeml#43]
see: https://github.com/scikit-activeml/annotlib

**Comment by tpham93** [comment]
Add a site for guidelines

**Comment by tpham93** [comment]
use readthedocs account of @mherde

**Comment by tpham93** [comment]
Private functions should start with an underscore. All non private functions should start without an underscore, check their inputs and should be imported, when importing the package.

**Comment by dakot** [comment]
done
