### ISSUE TITLE
List of methods and features for 1st release

### ISSUE THREAD

**Issue by dakot** [scikit-activeml/scikit-activeml#60]
* method name
* citation
* class name
* features

**Comment by dakot** [comment]
UncertaintySampling
* method: 
  * entropy
  * least_confident
  * margin_sampling
  * expected_average_precision
  * epistemic

Random

QBC
* method:
  * KL_divergence
  * vote_entropy
  
McPAL

XPAL

FourDS

ExpectedErrorReduction
* method:
  * emr
  * csl
  * log_loss

ALCE


to be implemented:
---
* DUAL: 
* Quire: Active Learning by Querying Informative and Representative Examples
* Margineantu
* LAL: Ksenia Konyushkova,  Raphael Sznitman,  and Pascal Fua.  Learning active learning fromdata
* FASS
* IWAL, ORIWAL (Region-Based Active Learning)
* Joshi et al VOI
* Graph density (Ebert 12)
* Dasgupta 08 (hierarchical clustering)

Multi-Label AL
* Survey: https://dl.acm.org/doi/pdf/10.1145/3379504 (Fig. 3)

What about Deep AL methods?
* Recent survey: https://arxiv.org/pdf/2008.07267.pdf (Fig. 2)
* Entropy
* BALD
* Batch-BALD
* sener 18: ACTIVELEARNING   FORCONVOLUTIONALNEURALNETWORKS: A CORE-SETAPPROACH

**Comment by mherde** [comment]
### to be implemented (multi-annotator):
- IE-Thresh
- IE-Adj-Cost
- ALIO
- ALC
- Proactive
- PMActive
- MaPAL
