### ISSUE TITLE
Handling sample_weight for SklearnClassifier

### ISSUE THREAD

**Issue by dakot** [scikit-activeml/scikit-activeml#84]
When Bagging classifier is executed with SklearnClassifier it passes sample_weight. But if estimator from SklearnClassifer does not support sample_weight, we run into problems.

@Pascal112 Provide minimal example

**Comment by dakot** [comment]
TODO: When fixing this issue, please note the workaround in #81

**Comment by Pascal112** [comment]
Example:
`X = [[1], [0]]`
`y = [1, 0]`
`clf = SklearnClassifier(GaussianProcessClassifier())`
`ensemble = SklearnClassifier(BaggingClassifier(clf))`
`ensemble.fit(X, y)`
`print(ensemble.is_fitted_)`

The wrapper passes always `sample_weight` even if it is not supported.

**Comment by mherde** [comment]
@Pascal112 Is `sample_weight` missing in your example?

**Comment by mherde** [comment]
There is already a detection whether an estimator supports `sample_weight`:

```
        if not has_fit_parameter(self.estimator, 'sample_weight') \
                and sample_weight is not None:
            raise ValueError(
                "{} does not support 'sample_weight'.".format(self.estimator))
```
Probably, I misunderstand the issue. Could one of you give a more detailed explanation @Pascal112 @dakot?

**Comment by Pascal112** [comment]
@mherde The BaggingClassifier passes np.ones to the wrapped GaussianProcessClassifier because he thinks that `sample_weight` is supported.
[github.com/scikit-learn/scikit-learn/blob/42aff4e2e/sklearn/ensemble/_bagging.py#L72](url)
Line 72, 99
