### ISSUE TITLE
More restrictive check_cost_matrix?

### ISSUE THREAD

**Issue by christoph14** [scikit-activeml/scikit-activeml#85]
- Should each cost matrix contain at least one value > 0?
- Should check_cost_matrix allow negative costs?

**Comment by mherde** [comment]
We could add additional parameters:

- `contains_non_zero` with default `False`,
- `only_non_negative` with default `False'.

What do you think @dakot @christoph14 ?

**Comment by mherde** [comment]
If we set default=True, we would need to pass through arguments for all base classifiers to change these default values. Therefore, I would propose to set default=False for the three new parameters in cost_matrix. What do you think @dakot @christoph14 ?

**Comment by dakot** [comment]
With false, trigger warning
